apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-staging-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: registry.tanzu.dk/webinars/app:sha-83117299e10c8b32021e6f1ab7dc50d45d384108
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 5000

