apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-staging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: registry.tanzu.dk/webinars/app:sha-d4088b71b9a2302e074a4f8aaf353f1f3f7a2510
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 5000

