apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-staging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: registry.tanzu.dk/webinars/app:sha-0afec7b3b6f7a94496a63aada2784c98d9dad5a3
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 5000

