apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-staging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: registry.tanzu.dk/webinars/app:sha-76255dfede5af17e36d0aa475be986e860f79e45
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 5000

